sudo: false
language: node_js
node_js:
    - '10'
env:
    matrix:
        - DATABASE_URL=postgres://postgres@localhost:5432/unleash_test TEST_DATABASE_URL=postgres://postgres@localhost:5432/unleash_test
    global:
        secure: HyWYh1dbUfe2yPF9ZdcdA/IVGyNWmJmpuaRvRGnnpO63/5Y0KT6/hyL6nZ4YJ7Wr/KEt4eMJBJsnzaCFtiqNA3cWyyprzXJButw0o8C6dfd/9jOleisuvdqndu92RqDKIIq2EjHVq3sd6B8uGyiOlkMsyFH57O/V+xHW8MYLnaQ=
before_install: npm install -g greenkeeper-lockfile@1
before_script:
    - psql -c 'create database unleash_test;' -U postgres
    - greenkeeper-lockfile-update
script: yarn run test:coverage
after_script: greenkeeper-lockfile-upload
after_success:
    - yarn run test:coverage-report
notifications:
    slack:
        secure: MroremSKwtQkwPbrXjgs9hIqKTCDKk7bAIXXzjcS6wXC9uRaFgwFaW8oO3vBxtWa4BL44EQBLE/rboWgqFER62+XgXNgEqGZqrcJHJvby4r+dUNMPI64OZvWdIiydIYxLo8C1C4x5PqBup0xuLq8h/SBnNvA2NLgkjuvzOi+v/Q=
addons:
  postgresql: '11'
cache:
    yarn: true
deploy:
    # deploy doc on master to production
    - provider: script
      script: bash scripts/deploy-docs.sh
      on:
          branch: master
