web:
  build: .
  command: npm run migrate-and-start
  ports:
    - "4242:4242"
  links:
    - db
  environment:
    DATABASE_URL: postgres://postgres:unleash@db/postgres
db:
  expose:
    - "5432"
  image: postgres:9.3
