name: Heroku Postgres Reset

on:
  workflow_dispatch:
  schedule:
    # run every day at midnight
    - cron: "0 0 * * *"

jobs:
  reset-postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          justlogin: true
      - name: Reset Postgres
        run: |
          heroku pg:reset DATABASE --app unleash --confirm unleash
